///*
// * LoginScreen.java
// *
// * Created on Aug 7, 2010, 8:00:46 PM
// */

//package login;

///**
// *
// * @author renweibo
// */
//public class LoginScreen extends javax.swing.JDialog {
//    private static final long serialVersionUID = 1L;
//    /** Creates new form LoginScreen */
//    public LoginScreen(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//    }

//    /** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
//    private void initComponents() {
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        btnLogin = new javax.swing.JButton();
//        userName = new javax.swing.JTextField();
//        password = new javax.swing.JPasswordField();
        

//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//        setTitle("Login");
//        setResizable(false);

//        jLabel1.setText("Username: ");

//        jLabel2.setText("Password: ");

//        btnLogin.setText("Login");

//        userName.setColumns(15);

//        password.setColumns(15);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(27, 27, 27)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jLabel1)
//                        .addGap(17, 17, 17)
//                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jLabel2)
//                        .addGap(17, 17, 17)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(btnLogin)
//                            .addComponent(password))))
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );

//        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {password, userName});

//        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(12, 12, 12)
//                        .addComponent(jLabel1))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(9, 9, 9)
//                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(9, 9, 9)
//                        .addComponent(jLabel2))
//                    .addGroup(layout.createSequentialGroup()
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
//                .addComponent(btnLogin)
//                .addContainerGap())
//        );

//        pack();
//    }

//    /**
//    * @param args the command line arguments
//    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                LoginScreen dialog = new LoginScreen(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

//    // Variables declaration - do not modify
//    javax.swing.JButton btnLogin;
//    javax.swing.JLabel jLabel1;
//    javax.swing.JLabel jLabel2;
//    javax.swing.JPasswordField password;
//    javax.swing.JTextField userName;
//    // End of variables declaration

//}

using System;
using UnityEngine;
using System.Collections;

public class LoginScreen : UIBase
{
    public event EventHandler Login;

    public UIInput name;
    public UIInput pwd;

    protected override void Awake()
    {
        base.Awake();

        if(null == name)
        {
            name = transform.FindChild("LblName").GetComponent<UIInput>();
            
        }

        if(null == pwd)
        {
            pwd = transform.FindChild("LblPwd").GetComponent<UIInput>();
        }
    }

    public void BtnLoginClick()
    {
        string mName = name.value;
        string mPwd = pwd.value;
        EventArgs args = new LoginArgs(mName, mPwd);
        if(Login != null) Login(this, args);
    }

    public void BtnRegisterClick()
    {

    }
}

public class LoginArgs : EventArgs
{
    public string Name { get; private set; }
    public string Pwd { get; private set; }

    public LoginArgs(string name, string pwd)
    {
        this.Name = name;
        this.Pwd = pwd;
    }
}

